
<?php 
/* Template Name: Certificate Page*/

get_header();
?>


<!-- service area start -->
<section class="about-area ptb--100">
  <div class="container">
    
      <div class="col-md-12 col-sm-12 col-xs-12">
	   <h1 class="sub-page-title" style="text-align: center;">Random Number Generator Certificate</h1>
<p class="terms-page-p">This is to certify that iTech Labs has evaluated the Random Number Generator (RNG) by CASHGRAIL Private Limited and found that the RNG complies with the relevant standards. *</p>
<p class="terms-page-p">Operator: CASHGRAIL Private Limited<br>
Operator URL: <a href="https://ludosupreme.in/">https://ludosupreme.in</a><br>
Software provider: CASHGRAIL Private Limited<br>
Software provider URL: <a href="https://www.ludosupreme.in/">https://ludosupreme.in/</a></p><br>
<p class="terms-page-p">The RNG uses a well-known algorithm to generate random numbers. The numbers generated by this RNG have passed Marsaglia's "diehard" tests for statistical randomness.</p>
<p class="terms-page-p">iTech Labs has also evaluated scaling for Ludo game. The scaling tests were conducted on large enough samples to give the calculations sufficient statistical power.</p>
<p class="terms-page-p">iTech Labs has found that the number sequences are unpredictable, non-repeatable and uniformly distributed. The certified code for the RNG has been fingerprinted.</p>
<p class="terms-page-p"><a href="https://www.ludosupreme.com/assets/img/RNG_Certificate_UK_CashGrailPrivateLimited_01May20.pdf" target="_blank" rel="noopener">Click here to view the Original iTech Labs Certificate.</a></p>
<br><img class=" wp-image-194 aligncenter certificate-img" src="http://localhost/sitecheck/wp-content/uploads/2021/08/rng_certificate.jpg" alt=""/> 
	  
	  
	  </div>
	</div>
</section>


<?php
get_footer();
?>